---
ID: "2b3f83d3-765e-4085-9dc4-bbe08817f086"
Parent: "53280367-a845-4413-856f-418557c98ee2"
Template: "53280367-a845-4413-856f-418557c98ee2"
Path: /sitecore/templates/Project/Sitecore/Home/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {25D85D7B-44CA-4FE6-A1CC-FECCFFACA95C}
    {C14B6289-8AC2-439C-9E5B-40DE9F820C3F}
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{BCFC7537-EFF4-434C-96F5-BF4F55FD175B}" />
      <d
        id="{0B4A31C9-712D-4578-A396-2DDC0F34B63A}"
        l="{72C595AD-68BB-44BC-B5CD-2A857039515F}" />
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190408T214105Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d8c8f548-91c9-4004-9705-ff860c709265"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20200710T194504Z
